function load_selVisMeas2(handles)

popuplist2 = [];
popuplist = handles.selVisMeas.String;
pop = {'CV-ratio of feature weights [Overall Mean]', ...
       'CV-ratio of feature weights [Grand Mean]', ...
       'Feature selection probability [Overall Mean]', ...
       'Probability of feature reliability (95%-CI) [Grand Mean]', ...
       'Sign-based consistency -log10(P value)', ...
       'Sign-based consistency -log10(P value, FDR)', ...
       'Analytical -log10(P Value) for Linear SVM [Grand Mean]', ...
       'Analytical -log10(P Value, FDR) for Linear SVM [Grand Mean]'}; 
   
%vals = [2 2 .5 .5 -log10(0.05) -log10(0.05) -log10(0.05) -log10(0.05)];
cnt=1;
for i=1:numel(popuplist)
    if any(strcmp(pop, popuplist{i}))
        popuplist2{cnt}= popuplist{i}; 
        cnt=cnt+1;
    end
end
handles.selVisMeas2.String = popuplist2;