y=122;

colors = [rgb('Purple'); rgb('Red'); rgb('MediumSeaGreen'); rgb('DarkGreen')];
Lg1 = 'bvFTD classifier';
Lg2 = 'Schizophrenia classifier';
Lg3 = 'MCI/Early AD classifier';
Lg4 = 'Established AD classifier';
Lg = {Lg1, Lg2, Lg3, Lg4};

Tr1 = 0;
Tr2 = 0.8;
Tr3 = 0.8;
Tr4 = 0.8;
Tr = [Tr1 Tr2 Tr3 Tr4];

figure;
spider_plot( ROIPerc(1:y,:)', ...
    'AxesLabels', L(1:y), ...
    'AxesLimits', [zeros(1,y); 100*ones(1,y)], ...
    'AxesShadedLimits', [zeros(1,y); 100*ones(1,y)], ...
    'AxesInterval', 10, ...
    'AxesLabelsEdge',' none', ...
    'AxesColor', rgb('Gainsboro'), ...
    'AxesDisplay', 'one', ...
    'AxesLabelsOffset', 0.05, ...
    'LabelFontSize', 7, ...
    'AxesHorzAlign', 'quadrant', ...
    'AxesVertAlign', 'quadrant', ...
    'AxesLabelsRotate', 'on', ...
    'AxesDirection', 'reverse', ...
    'LineTransparency', Tr, ...
    'Marker','none', ...
    'AxesPrecision',0, ...
    'Color', colors);

legend(Lg,'Location','northeastoutside')
title('ROI Profiles [%ROI covered]');

figure;
spider_plot( ROICVR(1:y,:)', ...
    'AxesLabels', L(1:y), ...
    'AxesLimits', [-6*ones(1,y); 6*ones(1,y)], ...
    'AxesShadedLimits', [-6*ones(1,y); 6*ones(1,y)], ...
    'AxesInterval', 10, ...
    'AxesLabelsEdge',' none', ...
    'AxesColor', rgb('LightGrey'), ...
    'AxesDisplay', 'one', ...
    'AxesLabelsOffset', 0.05, ...
    'LabelFontSize', 7, ...
    'AxesHorzAlign', 'quadrant', ...
    'AxesVertAlign', 'quadrant', ...
    'AxesLabelsRotate', 'on', ...
    'AxesDirection', 'reverse', ...
    'LineTransparency', 0.5, ...
    'Marker','none', ...
    'Color', colors);

legend(Lg,'Location','northeastoutside')
title('ROI Profiles [mean CVR]');
