function plot_spider_plot(tROI,rois, axes)
y=height(tROI);
% colors = [rgb('Purple'); rgb('Red'); rgb('MediumSeaGreen'); rgb('DarkGreen')];
% Lg1 = 'bvFTD classifier';
% Lg2 = 'Schizophrenia classifier';
% Lg3 = 'MCI/Early AD classifier';
% Lg4 = 'Established AD classifier';
% Lg = {Lg1, Lg2, Lg3, Lg4};
%
% Tr1 = 0;
% Tr2 = 0.8;
% Tr3 = 0.8;
% Tr4 = 0.8;
% Tr = [Tr1 Tr2 Tr3 Tr4];
%
% figure;



tROI.Properties.RowNames = tROI.AnatomicalRegion;


for i=1:height(rois)
    lbl = rois.ROIabbr{i};
    try rois.tROI(i) = table2array(tROI(lbl, 6)); catch; end
end
rois(rois.tROI==0,:) = [];

P = rois.tROI';
%             y=120;
% spider_plot(P, ...
%     'AxesLabels', rois.Var2, ...
%     'AxesLimits', [zeros(1,y); 100*ones(1,y)], ...
%     'AxesShadedLimits', [zeros(1,y); 100*ones(1,y)], ...
%     'AxesInterval', 10, ...
%     'AxesLabelsEdge',' none', ...
%     'AxesColor', rgb('Gainsboro'), ...
%     'AxesDisplay', 'one', ...
%     'AxesLabelsOffset', 0.05, ...
%     'LabelFontSize', 7, ...
%     'AxesHorzAlign', 'quadrant', ...
%     'AxesVertAlign', 'quadrant', ...
%     'AxesLabelsRotate', 'on', ...
%     'AxesDirection', 'reverse', ...
%     'Marker','none', ...
%     'AxesPrecision',0, ... %'Color', colors, ...
%     'Axesobject', axes);
% figure;
spider_plot(P, ...
    'AxesLabels', rois.ROIabbr,...
    'AxesLimits', [zeros(1,y); 100*ones(1,y)], ...
    'AxesShadedLimits', [zeros(1,y); 100*ones(1,y)], ...
    'AxesInterval', 1, ...
    'AxesLabelsEdge','none', ...
    'AxesDisplay', 'one', ...
    'AxesLabelsOffset', 0.05, ...
    'AxesFontSize', 12,...
    'LabelFontSize', 9, ...
    'LineWidth',2,...
    'FillOption', 'on',...
    'MarkerSize', 18,...
    'AxesHorzAlign', 'quadrant', ...
    'AxesVertAlign', 'quadrant', ...
    'AxesLabelsRotate', 'on', ...
    'AxesDirection', 'normal', ...
    'AxesPrecision',0,...
    'AxesZero','on',...
    'AxesLabelsRotate','on', ...
    'AxesOffset',1, ...
    'Axesobject', axes);


% legend(Lg,'Location','northeastoutside')
% title('ROI Profiles [%ROI covered]');

% figure;
% spider_plot( ROICVR(1:y,:)', ...
%     'AxesLabels', L(1:y), ...
%     'AxesLimits', [-6*ones(1,y); 6*ones(1,y)], ...
%     'AxesShadedLimits', [-6*ones(1,y); 6*ones(1,y)], ...
%     'AxesInterval', 10, ...
%     'AxesLabelsEdge',' none', ...
%     'AxesColor', rgb('LightGrey'), ...
%     'AxesDisplay', 'one', ...
%     'AxesLabelsOffset', 0.05, ...
%     'LabelFontSize', 7, ...
%     'AxesHorzAlign', 'quadrant', ...
%     'AxesVertAlign', 'quadrant', ...
%     'AxesLabelsRotate', 'on', ...
%     'AxesDirection', 'reverse', ...
%     'LineTransparency', 0.5, ...
%     'Marker','none', ...
%     'Color', colors);
%
% legend(Lg,'Location','northeastoutside')
% title('ROI Profiles [mean CVR]');
end
