function NM_out = train_model(NM, analind, ovrwrtfl, CV2x1, CV2x2, CV2y1, CV2y2, preprocmaster)



% %%%%%%%%%%%%%%%%%%%%%%%%% INITIALIZE NeuroMiner %%%%%%%%%%%%%%%%%%%%%%%%%
if ischar(preprocmaster) && exist(preprocmaster,'file')
    preprocmat = load(preprocmaster); lfl = 2; preprocmat = preprocmat.featmat;
else
    preprocmat = []; lfl = 1;
end

action = struct('addrootpath',1, ...
                'addDRpath',1, ...
                'addMIpath',1, ...
                'addLIBSVMpath',1, ...
                'addLIBLINpath',1, ...
                'addMikeRVMpath',1, ...
                'all',1);

nk_Initialize(action)

% %%%%%%%%%%%%%%%%%%%%%%%%% SETUP PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%
inp = struct('analind',			analind, ...
				'lfl',			lfl, ...
				'gdmat',		[], ...
				'gdanalmat', 	[], ...
				'varstr', 		[], ...
				'concatfl', 	[], ...
				'ovrwrt', 		ovrwrtfl, ...
				'update', 		true, ...
                'HideGridAct',  false, ...
                'batchflag',    false);
				
inp.GridAct = true(CV2x1,CV2x2);
inp.preprocmat = preprocmat;                            
inp = nk_GetAnalModalInfo_config(NM, inp);
                                
[inp, act, NM_out] = nk_MLOptimizerPrep(6, inp, 'train model');

end
